from __future__ import annotations

"""Canonical speech-language catalogue used by recognition, profiles and validation.

The codes mirror the multilingual Whisper tokenizer language catalogue.  Keeping
this list in one module prevents the UI and persistence validators from drifting
apart when languages are added.
"""

WHISPER_LANGUAGE_NAMES: dict[str, str] = {
    "en": "English",
    "zh": "中文",
    "de": "Deutsch",
    "es": "Español",
    "ru": "Русский",
    "ko": "한국어",
    "fr": "Français",
    "ja": "日本語",
    "pt": "Português",
    "tr": "Türkçe",
    "pl": "Polski",
    "ca": "Català",
    "nl": "Nederlands",
    "ar": "العربية",
    "sv": "Svenska",
    "it": "Italiano",
    "id": "Bahasa Indonesia",
    "hi": "हिन्दी",
    "fi": "Suomi",
    "vi": "Tiếng Việt",
    "he": "עברית",
    "uk": "Українська",
    "el": "Ελληνικά",
    "ms": "Bahasa Melayu",
    "cs": "Čeština",
    "ro": "Română",
    "da": "Dansk",
    "hu": "Magyar",
    "ta": "தமிழ்",
    "no": "Norsk",
    "th": "ไทย",
    "ur": "اردو",
    "hr": "Hrvatski",
    "bg": "Български",
    "lt": "Lietuvių",
    "la": "Latina",
    "mi": "Māori",
    "ml": "മലയാളം",
    "cy": "Cymraeg",
    "sk": "Slovenčina",
    "te": "తెలుగు",
    "fa": "فارسی",
    "lv": "Latviešu",
    "bn": "বাংলা",
    "sr": "Српски",
    "az": "Azərbaycanca",
    "sl": "Slovenščina",
    "kn": "ಕನ್ನಡ",
    "et": "Eesti",
    "mk": "Македонски",
    "br": "Brezhoneg",
    "eu": "Euskara",
    "is": "Íslenska",
    "hy": "Հայերեն",
    "ne": "नेपाली",
    "mn": "Монгол",
    "bs": "Bosanski",
    "kk": "Қазақша",
    "sq": "Shqip",
    "sw": "Kiswahili",
    "gl": "Galego",
    "mr": "मराठी",
    "pa": "ਪੰਜਾਬੀ",
    "si": "සිංහල",
    "km": "ខ្មែរ",
    "sn": "chiShona",
    "yo": "Yorùbá",
    "so": "Soomaali",
    "af": "Afrikaans",
    "oc": "Occitan",
    "ka": "ქართული",
    "be": "Беларуская",
    "tg": "Тоҷикӣ",
    "sd": "سنڌي",
    "gu": "ગુજરાતી",
    "am": "አማርኛ",
    "yi": "ייִדיש",
    "lo": "ລາວ",
    "uz": "Oʻzbekcha",
    "fo": "Føroyskt",
    "ht": "Kreyòl ayisyen",
    "ps": "پښتو",
    "tk": "Türkmençe",
    "nn": "Nynorsk",
    "mt": "Malti",
    "sa": "संस्कृतम्",
    "lb": "Lëtzebuergesch",
    "my": "မြန်မာဘာသာ",
    "bo": "བོད་སྐད་",
    "tl": "Tagalog",
    "mg": "Malagasy",
    "as": "অসমীয়া",
    "tt": "Татарча",
    "haw": "ʻŌlelo Hawaiʻi",
    "ln": "Lingála",
    "ha": "Hausa",
    "ba": "Башҡортса",
    "jw": "Basa Jawa",
    "su": "Basa Sunda",
    "yue": "粵語",
}

SUPPORTED_SPEECH_LANGUAGE_CODES = frozenset(WHISPER_LANGUAGE_NAMES)

if len(SUPPORTED_SPEECH_LANGUAGE_CODES) != 100:  # defensive guard against accidental edits
    raise RuntimeError("The LocalVoice Whisper language catalogue must contain exactly 100 language codes.")
